### ISSUE TITLE
I have problems with this error for awhile now

### ISSUE THREAD

**Issue by HabedyOmid** [srmklive/laravel-ecommerce#5]
(1/1) BadMethodCallExceptionMethod 

[getCheckoutData] does not exist.
--

this occurs while the express checkout route is triggered. basically the errors is inside getExpressCheckout() function on second line:

$recurring = ($request->get('mode') === 'recurring') ? true : false;

**Comment by srmklive** [comment]
Not the right repo. Kindly post this in the issue section for this repo (https://github.com/srmklive/laravel-paypal-demo)
